config/routes.rb
BookStore::Application.routes.draw do
  resources :books

  devise_for :users
    devise_scope :user do
      get "sign_in", :to => "devise/sessions#new"
   end
  root :to => "books#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :desc, :name
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :name, :price, :quantity,:author_id,:location_id
  belongs_to :author
  belongs_to :location
  validates :name, :presence => { :message => "Please enter a book name" },:uniqueness =>{:scope=> :author_id,:message=>"Book name has already been taken"}
  validates :price, :presence => { :message => "Please enter a book price" }
  validates :quantity, :presence => { :message => "Please enter a book quantity" }
  validates_numericality_of :quantity, :only_integer => true
  validates_numericality_of :price
  validates :location_id, :presence => { :message => "Please enter a book location" }
  validates :author_id, :presence => { :message => "Please enter a book author" }

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :desc, :name
  has_many:books

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name,:last_name
  # attr_accessible :title, :body
  has_many :posts,:dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!
  # GET /books
  # GET /books.json
  def index
    if params[:order_by] == "author"
      @books = Book.order("authors.name").all(:include => ["author","location"])
    elsif params[:order_by] == "location"
      @books = Book.order("locations.name").all(:include => ["author","location"])
    elsif params[:order_by] == "price_low"
      @books = Book.order("books.price").all(:include => ["author","location"])
    elsif params[:order_by] == "price_high"
      @books = Book.order("books.price desc").all(:include => ["author","location"])
    else
      @books = Book.order("updated_at DESC").all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div style="padding: 25px;width: 400px;" id="bookForm">
  <%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :author %><br />
      <%= select("book", "author_id", Author.all.collect {|a| [ a.name, a.id ] }, { :include_blank => 'Select Book Author' })%>
    </div>
    <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :quantity %><br />
      <%= f.number_field :quantity %>
    </div>
    <div class="field">
      <%= f.label :location_id %><br />
      <%= select("book", "location_id", Location.all.collect {|a| [ a.name, a.id ] }, { :include_blank => 'Select Book Location' })%>
    </div>
    <div class="actions">
      <%= submit_tag("Save", :id=>"book_submit",:class => "btn-share")%>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>
<div style="margin: 10px;width: 500px;text-align: center">
  <%= link_to 'Show', @book %> | <%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<div id="wrapper-contents" class="clearfix">
  <p><h2>Book Listing</h2></p>
<table cellpadding="2" cellspacing="2" border="1 px solid;" style="width: 900px;">
  <tr>
    <td colspan="2" class="darkGray"><%= link_to 'Sort by Author', books_path(:order_by => "author") %></td>
    <td colspan="2" class="darkGray"><%= link_to 'Sort by Price low', books_path(:order_by => "price_low") %></td>
    <td colspan="2" class="darkGray"><%= link_to 'Sort by Price high', books_path(:order_by => "price_heigh") %></td>
    <td colspan="2" class="darkGray"><%= link_to 'Sort by Location', books_path(:order_by => "location") %></td>
  </tr>
  <tr>
    <th>Name</th>
    <th>Author</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Location</th>
    <th colspan="3"></th>
  </tr>
  <% unless @books.blank? %>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author.name %></td>
        <td><%= book.price %></td>
        <td><%= book.quantity %></td>
        <td><%= book.location.name%></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <%else%>
    <tr>
      <td colspan="8">No Books Available</td>
    </tr>
  <%end%>
</table>
</div>
<br />
<%= link_to 'Add New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<div style="margin: 10px;width: 500px;text-align: center">
  <%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div style="margin: 10px;padding: 10px;">
  <p>
    <b>Name:</b>
    <%= @book.name %>
  </p>
  <p>
    <b>Author:</b>
    <%= @book.author.name %>
  </p>
  <p>
    <b>Price:</b>
    <%= @book.price %>
  </p>
  <p>
    <b>Quantity:</b>
    <%= @book.quantity %>
  </p>
  <p>
    <b>Location:</b>
    <%= @book.location.name %>
  </p>
</div>
<div style="margin: 10px;width: 500px;text-align: center">
  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Back', books_path %>
</div>

app/views/layouts/_footer.html.erb
<div class="clear"></div>
<div id="footer">
  Copyright © BookStore 2013
</div><!--footer-->

app/views/layouts/_header.html.erb
<div id="header">
  <h2 class="logo"> Book Store </h2>
  <div class="setting" id="controlS">
    <% if current_user %>
      <span id="user_welcome" class="user-welcome">Welcome <%= current_user.email %></span> | <%= link_to 'Sign Out', destroy_user_session_path(),:method=>'delete'%>
    </div>
  <%else%>
    <%= link_to "Sign up", new_registration_path(resource_name) %> | <%= link_to "Sign in", new_session_path(resource_name) %>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
    <title>Book Store</title>
    <%= stylesheet_link_tag 'application'%>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <!-- wrapper start -->
    <div id="wrapper">
      <div id="header">
        <!-- header Will render here -->
        <%= render :partial=>"layouts/header" %>
        <!-- header end -->
      </div>
      <!-- content start -->
      <div  id="container" class="clearfix">
        <%= yield %>
      </div>
      <!-- content end -->
      <%= render :partial=>"layouts/footer" %>
    </div><!--wrapper ends-->
  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>